name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd KyuNetworkExtensions-Client
          xcodebuild clean build -scheme KyuNetworkExtensions-Client -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
